version: '3.3'
services:
  db:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo

volumes:
  mongo:

# This configuration doesn't support transactions
# For transactions replica set must be configured
# See: https://flowygo.com/en/blog/mongodb-and-docker-how-to-create-and-configure-a-replica-set/
# See: https://github.com/alefiori82/mongo-replica-boilerplate